# Generated by Django 3.1.3 on 2020-11-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['categoryId'],
            },
        ),
    ]
