# Generated by Django 3.1.3 on 2020-11-24 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('bandId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['bandId'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['categoryId'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=60)),
                ('imageUrl', models.CharField(max_length=300)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.band')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'ordering': ['productId'],
            },
        ),
    ]
